In [1]:
import pandas as pd
from pathlib import Path

data_dir = Path("../data/processed")

files = [
    "day9_random_forest_evaluation.csv",
    "day10_xgboost_evaluation.csv",
]

for filename in files:
    path = data_dir / filename

    print(f"\n--- {filename} ---")

    if path.exists():
        result = pd.read_csv(path)
        print("Shape:", result.shape)
        print("Columns:", result.columns.tolist())
        display(result.head())
    else:
        print("File not found:", path)

--- day9_random_forest_evaluation.csv ---
Shape: (1, 4)
Columns: ['Model', 'MAE', 'RMSE', 'sMAPE']

           Model         MAE        RMSE      sMAPE
0  Random Forest  710.627851  1036.48145  10.514257

--- day10_xgboost_evaluation.csv ---
Shape: (1, 4)
Columns: ['Model', 'MAE', 'RMSE', 'sMAPE']

     Model         MAE        RMSE      sMAPE
0  XGBoost  697.105896  999.247154  10.324177

In [2]:
from pathlib import Path
import pandas as pd

data_dir = Path("../data/processed")

rf = pd.read_csv(data_dir / "day9_random_forest_evaluation.csv")
xgb = pd.read_csv(data_dir / "day10_xgboost_evaluation.csv")

comparison = pd.concat([rf, xgb], ignore_index=True)
comparison = comparison.sort_values("MAE").reset_index(drop=True)

comparison.to_csv(
    data_dir / "day14_model_selection.csv",
    index=False
)

display(comparison)

           Model         MAE         RMSE      sMAPE
0        XGBoost  697.105896   999.247154  10.324177
1  Random Forest  710.627851  1036.481450  10.514257

### Day 14 — Model Selection

- Compared Random Forest and XGBoost using the same temporal validation setup.
- XGBoost achieved an MAE of 697.11, RMSE of 999.25, and sMAPE of 10.32%.
- Random Forest achieved an MAE of 710.63, RMSE of 1036.48, and sMAPE of 10.51%.
- XGBoost performed better across all three evaluation metrics on this holdout.
- XGBoost is selected as the current candidate forecasting model, subject to further validation and operational testing.
- Store-level errors should continue to be monitored because aggregate metrics may hide poor performance at individual stores.